spiderJson = {"nodes":[
{"weight":7,"rank":0.0, "id":1, "url":"https://jetpackages.com"},
{"weight":1,"rank":19.0, "id":2, "url":"https://jetpackages.com/topics/android-service-overlay-compose"},
{"weight":1,"rank":19.0, "id":3, "url":"https://jetpackages.com/topics/android-etag-caching"},
{"weight":1,"rank":19.0, "id":4, "url":"https://jetpackages.com/topics/cover-buddy"},
{"weight":1,"rank":19.0, "id":5, "url":"https://jetpackages.com/topics/order-pause"},
{"weight":1,"rank":19.0, "id":6, "url":"https://jetpackages.com/topics/tilttok"},
{"weight":1,"rank":19.0, "id":7, "url":"https://jetpackages.com/resume-studio"},
{"weight":1,"rank":0.0, "id":9, "url":"https://jetpackages.com/coverletter"}],
"links":[
{"source":0,"target":0,"value":3},
{"source":0,"target":1,"value":3},
{"source":0,"target":2,"value":3},
{"source":0,"target":3,"value":3},
{"source":0,"target":4,"value":3},
{"source":0,"target":5,"value":3},
{"source":0,"target":6,"value":3},
{"source":1,"target":0,"value":3},
{"source":2,"target":0,"value":3},
{"source":3,"target":0,"value":3},
{"source":3,"target":7,"value":3},
{"source":4,"target":0,"value":3},
{"source":5,"target":0,"value":3},
{"source":6,"target":0,"value":3}]};